### PR TITLE
Depend on libgtk-3-0 | libgtk2.0-0, don't require both

### PR DESCRIPTION
**Pull request by ginggs**
Adapted from:
https://anonscm.debian.org/cgit/pkg-nvidia/nvidia-settings.git/commit/?id=ea169261264f7d8b80e3e091a131cb98343e7d3f
https://bugs.launchpad.net/ubuntu/+source/nvidia-settings/+bug/1736617
LP: #1736617

### CODE REVIEW

**Comment by jbicha** [comment]
It is not practical to run Ubuntu 18.04 without gtk3 installed. For instance, both supported web browsers, Firefox and Chromium use gtk3.

Therefore, I suggest you instead try something like the last 2 lines of
https://anonscm.debian.org/git/pkg-gnome/gnome-themes-standard.git/tree/debian/rules

**Comment by jbicha** [comment]
@ginggs Do you want to try my approach ^ instead?

**Comment by ginggs** [comment]
@jbicha No, it seems your approach depends on gtk3 only, not gtk3 **or** gtk2.

**Comment by ginggs** [comment]
@tseliot I've just pushed the commit with a change included in nvidia-settings 387.34-2 uploaded to Debian on 2018-03-06.

Let me know if you want this branch squashed and rebased.

**Comment by tseliot** [comment]
@ginggs sure, that would help, thanks.

**Comment by jbicha** [comment]
@ginggs Yes, that is intentional. You need to have gtk3 installed anyway. There's no reason someone would have gtk2 installed but not gtk3 in 2018.

**Comment by ginggs** [comment]
@jbicha nvidia-settings runs on Nvidia Jetson ARM boards, one might not need to have a web browser installed

**Comment by jbicha** [comment]
@ginggs Ok, but that's not much of a justification. gtk2 is being slowly removed from distros and doesn't have any advantages compared to gtk3 here.

**Pull request merged**
